# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

###############################################################################
# Jumpbox – Windows Server EC2 instance with public IP
###############################################################################

locals {
  common_tags = {
    Environment = var.environment
    ManagedBy   = "terraform"
    Project     = "evs-vcf9-automation"
  }

  # AWSCC resources expect tags as a list of {key, value} objects rather than
  # a map. Derive from common_tags so the two representations cannot drift.
  common_tags_list = [for k, v in local.common_tags : { key = k, value = v }]
}

# --- Latest Windows Server AMI ------------------------------------------------

data "aws_ami" "windows" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["Windows_Server-2025-English-Full-Base-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  filter {
    name   = "architecture"
    values = ["x86_64"]
  }
}

# --- Public Subnet for Jumpbox ------------------------------------------------

resource "aws_subnet" "jumpbox" {
  vpc_id                  = var.vpc_id
  availability_zone       = var.availability_zone
  cidr_block              = var.subnet_cidr
  map_public_ip_on_launch = true

  tags = merge(local.common_tags, { Name = "Jumpbox-Public-Subnet" })
}

resource "aws_route_table" "jumpbox" {
  vpc_id = var.vpc_id
  tags   = merge(local.common_tags, { Name = "Jumpbox-RTB" })
}

resource "aws_route_table_association" "jumpbox" {
  subnet_id      = aws_subnet.jumpbox.id
  route_table_id = aws_route_table.jumpbox.id
}

resource "aws_route" "jumpbox_igw" {
  route_table_id         = aws_route_table.jumpbox.id
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = var.internet_gateway_id
}

# --- Security Group -----------------------------------------------------------

resource "aws_security_group" "jumpbox" {
  name_prefix = "jumpbox-"
  description = "Security group for the Windows jumpbox"
  vpc_id      = var.vpc_id

  # Allow all traffic from within the VPC
  ingress {
    description = "All traffic from VPC CIDR"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = [var.vpc_cidr_block]
  }

  # All outbound
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(local.common_tags, { Name = "Jumpbox-SG" })
}

# Allow the jumpbox SG to reach resources in the VPC default SG
resource "aws_vpc_security_group_ingress_rule" "default_sg_from_jumpbox" {
  security_group_id            = var.vpc_default_security_group_id
  referenced_security_group_id = aws_security_group.jumpbox.id
  ip_protocol                  = "-1"
  description                  = "All traffic from Jumpbox SG"
}

# Allow the jumpbox SG to reach resources in the EVS SG (vCenter, SDDC Manager,
# VCF Installer, EVS hosts, etc.)
resource "aws_vpc_security_group_ingress_rule" "evs_sg_from_jumpbox" {
  security_group_id            = var.evs_security_group_id
  referenced_security_group_id = aws_security_group.jumpbox.id
  ip_protocol                  = "-1"
  description                  = "All traffic from Jumpbox SG"
}

# --- Key Pair -----------------------------------------------------------------
# Server-side generated by AWS; private key stored in SSM automatically
# at /ec2/keypair/<key_pair_id>

resource "random_id" "jumpbox_key_suffix" {
  byte_length = 4
}

resource "awscc_ec2_key_pair" "jumpbox" {
  key_name   = "Jumpbox-KeyPair-${random_id.jumpbox_key_suffix.hex}"
  key_type   = "rsa"
  key_format = "pem"

  tags = concat(local.common_tags_list, [{ key = "Name", value = "Jumpbox-KeyPair-${random_id.jumpbox_key_suffix.hex}" }])
}

# --- EC2 Instance -------------------------------------------------------------

resource "aws_instance" "jumpbox" {
  ami                         = data.aws_ami.windows.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.jumpbox.id
  vpc_security_group_ids      = [aws_security_group.jumpbox.id]
  key_name                    = awscc_ec2_key_pair.jumpbox.key_name
  associate_public_ip_address = true

  root_block_device {
    volume_size = 50
    volume_type = "gp3"
    encrypted   = true
  }

  metadata_options {
    http_tokens   = "required"
    http_endpoint = "enabled"
  }

  tags = merge(local.common_tags, { Name = "EVS-Jumpbox" })
}
